# use docker-compose
version: '3.8'
services:
  simulator:
    image: eachan10/rpg_trajectory_evaluation:melodic
    container_name: rpg_trajectory_evaluation
    stdin_open: true # keeps the standard input of the container open and allows interaction with the terminal.
    tty: true # allocates a pseudo-TTY for the container, which is required for running interactive shell commands in the container.
    volumes: # Mount the following volumes in the container
      - type: bind # Bind mount the host directory into the container
        source: $HOME/my_prjs/aQC_project/rpg_trajectory_evaluation
        target: /root/catkin_ws/src/rpg_trajectory_evaluation
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
    environment: # Set the following environment variables in the container
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - PULSE_SERVER=$PULSE_SERVER
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    devices: # Add the following devices to the container
      - /dev/dxg
    network_mode: host # Use the host network stack for the container
    command: zsh # Run the command "zsh" in the container/home/yichen/my_prjs/collaborative_exploration/autonomous_exploration_development_environment/src